--- 
title: "High School Students Performance Analysis"
author: "Group 6: Weisheng Chen & Zixiang Yin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Education is always a key factor in the development of a country. According to our investigation, statistics show that Portugal remains at a low education level in Europe. In 2006, the early school in Portugal has a dropping rate of 40% while the average is 15% for the whole Europe. Students failed many classes and the failure in two core classes, Math and Portuguese, was extremely serious. As Portuguese students have a high failure and drop-out rate, it is very important to figure out what factors have a positive/negative impact on students' performance in different subjects. Hence, we want to conduct students' performance analysis based on student data from two Portuguese schools and hope that we can extract useful information to help us understand how both academic-related and non-academic related factors influence a student's Math and Portuguese grades. In addition, we are also interested in exploring the difference between these two schools in terms of students' backgrounds and demographic information. \

Secondary education in Portugal consists of 3 years of schooling which is followed by higher education. Most students attend the public education system where they take several courses such as Science and Art. Mathematics and Portuguese(native language) are two core subjects. For each academic year, students are evaluated in three periods(from the first period to the third period). Exams are based on a 20-points grading scale where 0 is the lowest grade and 20 is the full point. In our project, we use data collected in the 2005 academic year from two public schools which include demographic, social and academic-related attributes. \

In the following chapters, we aim to carry out students' performance analysis and try to answer the following question:

   i. What is the difference between the two schools in terms of students’ background?
   ii. What are some factors that influence students’ academic performance?
   iii. Is there an interesting pattern in students’ grades throughout high school?

All of our work can be found in the Github repository: https://github.com/gbZachYin/StuPerfAnalysis